### ISSUE TITLE
Ansible in CloudShell appears to be broken

### ISSUE THREAD

**Issue by TomArcherMsft** [Azure/Ansible#24]
@hisasima @DavidLievrouw opened a [GitHub Issue in the Ansible developer documentation](https://github.com/MicrosoftDocs/azure-dev-docs/issues/708) about Ansible no longer working in Cloud Shell.

I tested a very simple Ansible playbook:

```yaml
- name: Create a resource group
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: tarcher-test-rg
        location: eastus
```

I see similar errors as them:
*An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.mgmt.monitor.version'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on cc-77654aed-c95b8b99d-hvlnm's Python /opt/ansible/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}*

**Comment by DavidLievrouw** [comment]
A temporary workaround, is to install a newer version.
- Check the current version with `ansible-playbook --version`: Results in `2.10.2`.
- Run:
  ```
  pip3 install 'ansible[azure]'
  curl -O https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
  pip3 install -r requirements-azure.txt
  ansible-galaxy collection install azure.azcollection
  ```
- Then close the cloud shell, and reopen it (required!). 
- Confirm with `ansible-playbook --version`: Results in `2.11.8`.

Then, I need to modify the playbook tasks, so that they use CLI as auth souce:

```yaml
auth_source: cli
```

e.g.
```yaml
- name: Create a resource group
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: tarcher-test-rg
        location: eastus
        auth_source: cli
```

Run the playbook again, it should work now.
